---
title: "SummarizedExperiment"
author: "Santiago Orozco"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Objeto SummarizedExperiment
Objeto de GRanges (genomic ranges)
Es un objeto que contiene datos de expresión genética y metadatos asociados.
ColData

## rtracklayer

---

'Copy permalink' es el link a la pagina específica en el tiempo. 


`View(objeto)` Para ver el objeto en una tabla 


Metadata


ìdentical(a, b)` para comparar dos objetos



## iSEE ()
Cómo visualizar los datos de los objetos. Es interactivo

`iSEE::iSEE(objeto)`

Sample assay plot 1 

Centrar, 
Escalar, dividir sobre la sd de cada gen


Guardar parámetro: Export > Display panel 
Cargar parámetros de figuras: 
settings
Descargar figuras de iSEE: Export > Display panel outputs, descargar las figuras que quieras en formato pdf. 

** `lobster::obj_size(objeto)` para ver el tamaño del objeto

## Ejercicio con iSEE

Debido a que al intentar descargar las figuras en formato no se pudo. Solo daba la opción de descargar como .html (en realidad marcaba com .htm) y a que al descargarlo era ilegible. Se procedió a realizar un screenshot de la figura y se guardó en formato .png. Ver carpeta de figuras `Fig`, los archivos `02.4-PCA_sce_layer.png` y `02.5-heatmap_sce_layer.png`
